name: Node CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: bun install and lint code
      run: |
        bun install
        bun run lint
      env:
        CI: true

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: bun install and test
      run: |
        bun install
        bun run test
      env:
        CI: true
        NODE_ENV: test

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: bun install and build
      run: |
        bun install
        bun run build
      env:
        CI: true
        NODE_ENV: prod
